// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3p8fDrSxDLl7dSBKdFNhMyh2rvZvXh9o',
    appId: '1:630305950405:web:1f414082bb27b2ef577eac',
    messagingSenderId: '630305950405',
    projectId: 'police-assistant-844f4',
    authDomain: 'police-assistant-844f4.firebaseapp.com',
    storageBucket: 'police-assistant-844f4.appspot.com',
    measurementId: 'G-Z621ZLRW2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWaIUtGjnqTT8g9MqYHe1ccPJ7qxalOVw',
    appId: '1:630305950405:android:71dc1084288fe532577eac',
    messagingSenderId: '630305950405',
    projectId: 'police-assistant-844f4',
    storageBucket: 'police-assistant-844f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjSxW8KWRPUK9VaOGudYXEesWdyj36PIo',
    appId: '1:630305950405:ios:31e07dbf47db5530577eac',
    messagingSenderId: '630305950405',
    projectId: 'police-assistant-844f4',
    storageBucket: 'police-assistant-844f4.appspot.com',
    iosBundleId: 'com.example.policeAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjSxW8KWRPUK9VaOGudYXEesWdyj36PIo',
    appId: '1:630305950405:ios:31e07dbf47db5530577eac',
    messagingSenderId: '630305950405',
    projectId: 'police-assistant-844f4',
    storageBucket: 'police-assistant-844f4.appspot.com',
    iosBundleId: 'com.example.policeAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3p8fDrSxDLl7dSBKdFNhMyh2rvZvXh9o',
    appId: '1:630305950405:web:ec5cc3b368aefa55577eac',
    messagingSenderId: '630305950405',
    projectId: 'police-assistant-844f4',
    authDomain: 'police-assistant-844f4.firebaseapp.com',
    storageBucket: 'police-assistant-844f4.appspot.com',
    measurementId: 'G-WC4TB4W140',
  );

}